### ISSUE TITLE
Support for ResX localization!

### ISSUE THREAD

**Issue by da3dsoul** [nulastudio/NetCoreBeauty#10]
![explorer_2020-08-10_06-42-10](https://user-images.githubusercontent.com/5205810/89774873-ad155600-dad4-11ea-9b25-3e070d185c7d.png)
As you can see, ResX generates language code folders which have additional DLLs inside them. According to [this](https://docs.microsoft.com/en-us/dotnet/framework/resources/creating-satellite-assemblies-for-desktop-apps?redirectedfrom=MSDN), they are loaded in the same way that this does, so simply putting them inside the libraries folder would clean it up nicely.

EDIT: I noticed that it gets some of the files, but not all of them.... I wonder why....

**Comment by da3dsoul** [comment]
![explorer_2020-08-10_06-59-52](https://user-images.githubusercontent.com/5205810/89776109-3594f600-dad7-11ea-95de-eb6c291092a9.png)
That's what's left. It got Microsoft DLLs.

**Comment by da3dsoul** [comment]
It appears to take runtimepack.Microsoft.WindowsDesktop.App.Runtime runtimes and add `.resources.dll` to them. Unfortunately, the deps,json doesn't seem to list them.

**Comment by da3dsoul** [comment]
The dirty solution would be to check for the existence of these folders, see if they contain nothing but DLLs and move them. I just dumped all possible language codes from netcore.
[lang.txt](https://github.com/nulastudio/NetCoreBeauty/files/5050572/lang.txt)

**Comment by liesauer** [comment]
NetCoreBeauty analyses `deps.json` to detemine which should be moved. if they aren't moved, they must be not included in `deps.json`.

**Comment by liesauer** [comment]
but those files should be listed in `deps.json`. btw could you upload a test case?

**Comment by da3dsoul** [comment]
I'll see if I can make one. This particular project is 14 years old and been through a lot of changes.

**Comment by da3dsoul** [comment]
https://github.com/da3dsoul/LocalizationTest There you go. Verified. I noticed that for some reason, it creates a bunch of folders for cultures that aren't even supported.

**Comment by liesauer** [comment]
it looks like only the app's localization resources are listed in the `deps.json`. the libraries's localization resources aren't listed for some reason.

**Comment by da3dsoul** [comment]
Yeah, that's why I mentioned the "dirty solution". Ideally, those would be listed, but ideally, this project wouldn't need to be so complex to work.

**Comment by liesauer** [comment]
you are right, there is no need to generate those localization that we don't use at all. i will try re-adding those resources back to `deps.json` and see if the app still can read those localization strings.  in theory, this should work.

**Comment by liesauer** [comment]
try the latest [`v1.2.9`](https://www.nuget.org/packages/nulastudio.NetCoreBeauty/1.2.9)

**Comment by da3dsoul** [comment]
No change. I notice the build failed, as well, and that appears to be a deployment failure.

**Comment by liesauer** [comment]
> No change. I notice the build failed, as well, and that appears to be a deployment failure.

ignore the build. are you using Nuget? you need to upgrade the package.
```xml
<PackageReference Include="nulastudio.NetCoreBeauty" Version="1.2.9" />
```

**Comment by da3dsoul** [comment]
<details>
  <summary>Screenies!</summary>

![rider64_2020-08-14_09-08-30](https://user-images.githubusercontent.com/5205810/90252732-fedc1a00-de0d-11ea-966a-db0073170522.png)
![explorer_2020-08-14_09-09-08](https://user-images.githubusercontent.com/5205810/90252992-70b46380-de0e-11ea-95da-3d0e62c7ae1c.png)
![explorer_2020-08-14_09-09-17](https://user-images.githubusercontent.com/5205810/90253000-74e08100-de0e-11ea-9fbd-601d2664614f.png)

</details>
To show how I have it set up. I then publish with `dotnet publish -c Release -r win10-x64 -p:PublishTrimmed=false`

**Comment by liesauer** [comment]
have you  beauty this project before?( check if this is a file called `NetCoreBeauty`). if so, you need to set `<ForceBeauty></ForceBeauty>` to `True`, because NetCoreBeauty only beauty once.

**Comment by da3dsoul** [comment]
I deleted the build folder prior. Is it kept anywhere else?

**Comment by liesauer** [comment]
entire bin folder?

**Comment by da3dsoul** [comment]
Yes, though I didn't delete obj

**Comment by liesauer** [comment]
could you set `<BeautyLogLevel></BeautyLogLevel>` to `Info` and see what output?

**Comment by liesauer** [comment]
btw, could you upload your release?

**Comment by da3dsoul** [comment]
Found the issue. If I set `<BeautyExcludes>Shoko*.dll</BeautyExcludes>` it doesn't clean up the rest

**Comment by liesauer** [comment]
you need to set more specific rule.

**Comment by da3dsoul** [comment]
It also wasn't needed. It works, thanks
