### ISSUE TITLE
Application fails to run if PublishTrimmed=True

### ISSUE THREAD

**Issue by sitiom** [nulastudio/NetCoreBeauty#13]
Minimal reproduction: https://github.com/nulastudio/NetCoreBeauty/issues/10#issuecomment-671730525 with latest NetCoreBeauty version and `PublishTrimmed` set to `true`.

**Comment by liesauer** [comment]
it works for me. more details? logs, sdk version or anything.

![image](https://user-images.githubusercontent.com/8676741/103047434-7a24b800-45c6-11eb-8b92-904c590606c6.png)

**Comment by sitiom** [comment]
Strange, exact thing doesn't work for me.

SDK Version: 5.0.100
Built with `dotnet publish -r win-x64 --self-contained true -p:PublishTrimmed=True`

**Comment by liesauer** [comment]
looks like it's the sdk issue. the `5.0.100` sdk over-trims something and makes the app crashed(verified, still fails to run even though i disable `NetCoreBeauty`).



 
From: sitiom
Date: 2020-12-24 09:22
To: nulastudio/NetCoreBeauty
CC: L!εsAμεr; Comment
Subject: Re: [nulastudio/NetCoreBeauty] Application fails to run if PublishTrimmed=True (#13)
Strange, exact thing doesn't work for me.
SDK Version: 5.0.100
Built with dotnet publish -r win-x64 --self-contained true -p:PublishTrimmed=True

**Comment by liesauer** [comment]
see dotnet/sdk#14261

**Comment by sitiom** [comment]
That works for now, thanks.

**Comment by xdrie** [comment]
@sitiom What's the fix?

**Comment by liesauer** [comment]
> @sitiom What's the fix?

see this comment, https://github.com/dotnet/sdk/issues/14261#issuecomment-734446135
