### ISSUE TITLE
我尝试使用'框架依赖'的发布方式使用这个库,但是工作正常,这样做会有什么潜在的问题吗?

### ISSUE THREAD

**Issue by BigDream324** [nulastudio/NetCoreBeauty#14]
在repo的ReadMe中我看到说这个库的限制是只能使用在独立发布中, 但是经过我的实测,我使用框架依赖的发布方式也正常工作了,请问这样使用会有什么潜在的问题吗? 为什么readme中提到只能在独立发布中使用?

**Comment by liesauer** [comment]
当使用非`独立发布`发布时，工具现在会强制跳过执行，所以并不会造成潜在问题，相当于并没有经过工具的处理。由于corehost中的一个BUG（具体请看#1），工具必须依赖于`独立发布`，在发布时需要下载一个确定版本的打过补丁的`hostfxr`以消除这个BUG带来的影响（这个BUG的具体影响就是，必须要cd到软件根目录再运行程序，否则会找不到依赖文件导致报错），而`框架依赖`是不带`hostfxr`文件的，所以没办法工作于这个发布模式。

**Comment by liesauer** [comment]
`NetBeauty2` 已支持`框架依赖`模式。
