### ISSUE TITLE
BeautyHiddens options are ignored inside csproj file

### ISSUE THREAD

**Issue by Greendq** [nulastudio/NetCoreBeauty#16]
Uncommented <BeautyHiddens> section of the csproj file ignored - NCB leaves hostfxr.dll, hostpolicy.dll, *.deps.json and *.runtimeconfig.json files in the publish directory while I expected they will be hidden too.

Project uses .Net Core 3.1 executable target, NCB version 1.2.9.2.

**Comment by liesauer** [comment]
it works for me, have you enabled `Hidden items` option in File Explorer or using *nix?
`BeautyHiddens` option is literally hiding them, not moving them, and works under windows only.
![image](https://user-images.githubusercontent.com/8676741/104900289-da84fa80-59b6-11eb-9df6-c26694bd75b7.png)
![image](https://user-images.githubusercontent.com/8676741/104901063-d9a09880-59b7-11eb-9e9b-0705491a2805.png)

**Comment by Greendq** [comment]
Yes, I notified hidden attribute, but I expected they will be moved :)

I think, it is better to add a note in the description about this to remove misunderstanding.

Thank you!

**Comment by liesauer** [comment]
yeah, you are right!
