### ISSUE TITLE
Integrating in github workflow

### ISSUE THREAD

**Issue by easly1989** [nulastudio/NetCoreBeauty#17]
Hello there,
I'm building an app as part of my cusotm workflow on github.
I'm installing the CLI tool using this line
`dotnet tool install --global nulastudio.ncbeauty`

and then calling the ncbeauty using this other line
`ncbeauty --noflag --nopatch --hiddens "hostfxr;hostpolicy;*.deps.json;*.runtimeconfig*.json;*.config" ..\bin libs`

I'm getting this error

> It was not possible to find any compatible framework version
> The framework 'Microsoft.NETCore.App', version '2.1.0' was not found.
>  - The following frameworks were found:
>       5.0.2 at [C:\Users\runneradmin\AppData\Local\Microsoft\dotnet\shared\Microsoft.NETCore.App]
> 
> You can resolve the problem by installing the specified framework and/or SDK.
> 
> The specified framework can be found at:
> https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=2.1.0&arch=x64&rid=win10-x64
> Error: Process completed with exit code 1.

The app is a WPF Net5 app, and running the command from my local windows powershell is ok, but it seems to not work on the github workflow for some reason

Any suggestions on how I can solve the issue?
Thank you in advance

**Comment by liesauer** [comment]
the global tool is targeting at .NET Core `2.1`, so you need to download the `2.1.0` runtime before you can run. you should 
 have installed `2.1` sdk on your local pc so you can run it, haven't you? use `dotnet --info` to check. personally, i don't recommand installing a additional runtime just in order to run a tiny global tool(it's a wrapper basically), i prefer downloading the binary distribution from [Releases](https://github.com/nulastudio/NetCoreBeauty/releases) and then run it.

**Comment by liesauer** [comment]
btw, i have noticed that you have enabled `--nopatch` option, this will cause your application fails to run if pwd is not the same as the application location. more details about [this issue](https://github.com/nulastudio/NetCoreBeauty#how).

**Comment by easly1989** [comment]
I will remove the nopatch option and see if it may help.
Btw if to run it I have to install the 2.1 it may be a no-go for me.
Maybe i should go for the nuget package? and use the BeautyAfterTasks option?

**Comment by liesauer** [comment]
yes, you can reference the nuget package, but no need to use `BeautyAfterTasks`, this option is used for controling the execution time after publishing.

**Comment by easly1989** [comment]
If I want to make the output dir beautiful, even after a simple
build/rebuild I should go for the BeauryAfterTask option and specify
Compile or Build;Rebuild as the argument, or am I wrong?

(because I'm not publishing the code atm, just zipping the release build as
a part of the continuous development workflow)

Il Mer 10 Feb 2021, 09:55 L!εsAμεr <notifications@github.com> ha scritto:

**Comment by liesauer** [comment]
unfortunately, NetCoreBeauty only works after publishing, it won't run when build the project. it's force dependent on `Publish` task.

**Comment by easly1989** [comment]
Got it, I, ll try publishing in the workflow instead and hope for the best
Thanks for the support!
