### ISSUE TITLE
"Artifact does not exist. v5.0.4/win-x64" when packaging with .NET 5.0.4

### ISSUE THREAD

**Issue by Ellpeck** [nulastudio/NetCoreBeauty#18]
It seems like there are no patches for .NET 5.0.4 currently available.

**Comment by liesauer** [comment]
uploaded

**Comment by Ellpeck** [comment]
It still seems like it doesn't exist, I'm getting the same error. Do I need to update NetCoreBeauty?

**Comment by liesauer** [comment]
no, it will fetch the lastest artifacts automatically. can you show me the logs?

**Comment by Ellpeck** [comment]
Oh, it also seems to error on linux and mac.

```
patching hostfxr...
using compatible rid linux-x64 for linux-x64
Artifact does not exist. v5.0.4/linux-x64
patch failed
```

What are the effects of this step failing anyway? The final build still seems to work correctly.

**Comment by liesauer** [comment]
NetCoreBeauty does not have `5.x-linux` `5.x-osx` artifacts yet.

**Comment by liesauer** [comment]
if the app successfully running outside the `APP_BASE`(root of the app), then it should be OK. i successfully running one of my app with unpatched runtime `5.0.3` under windows, and it works fine,  even though i haven't heard any of the related issues have been fixed. you can have a try.
