### ISSUE TITLE
发布时报错 cannot find a compatible rid for win-x64

### ISSUE THREAD

**Issue by zgliubo** [nulastudio/NetCoreBeauty#19]
请问需要怎么设置下吗, 谢谢

**Comment by liesauer** [comment]
添加或修改以下配置到csproj文件
```xml
<BeautyLogLevel>Info</BeautyLogLevel>
```
然后把完整日志发给我看下

**Comment by zgliubo** [comment]
running ncbeauty...
checking runtime.*.json version...
fetch online runtime compatibility version failed
fixing C:\Users\fszx03\Desktop\Browser5\ConsoleApp2\bin\Release\net5.0\publish\ConsoleApp2.runtimeconfig.json
C:\Users\fszx03\Desktop\Browser5\ConsoleApp2\bin\Release\net5.0\publish\ConsoleApp2.runtimeconfig.json fixed
fixing C:\Users\fszx03\Desktop\Browser5\ConsoleApp2\bin\Release\net5.0\publish\ConsoleApp2.deps.json
fxr v5.0.4/win-x64 detected in C:/Users/fszx03/Desktop/Browser5/ConsoleApp2/bin/Release/net5.0/publish/ConsoleApp2.deps.json
patching hostfxr...
read json failed: C:\Users\fszx03\AppData\Local\Temp/NetCoreBeauty/artifacts/runtime.compatibility.json : open C:\Users\fszx03\AppData\Local\Temp/NetCoreBeauty/artifacts/runtime.compatibility.json: The system cannot find the file specified.
cannot find a compatible rid for win-x64

**Comment by liesauer** [comment]
添加以下配置
```xml
<GitCDN>https://gitee.com/liesauer/HostFXRPatcher</GitCDN>
```
然后把`C:\Users\fszx03\AppData\Local\Temp/NetCoreBeauty`文件夹清空，重新发布即可

**Comment by liesauer** [comment]
工具默认从`GitHub`获取配置信息，对于我们国内的用户可能会失败，所以要切换到国内的`Gitee`镜像库。

**Comment by zgliubo** [comment]
非常感谢您的热心解答. 怪我没认真看文档. 点个赞!

**Comment by liesauer** [comment]
我也更新了readme，在前面添加了提示，不然关于`GitCDN`的设置在很后的地方，不一定所有人都能注意到。
