### ISSUE TITLE
请问有菜鸟级指导博客或视频吗

### ISSUE THREAD

**Issue by zhangbest5** [nulastudio/NetCoreBeauty#20]
大佬好，是国人吧，真是厉害，能写这么优秀的东西
我这边技术水平有限，无法实现vs自动发布时使用beauty
发布完，还是原来的样子
使用的是vs 2019，windows 10, core 3.1
现在只能在代码发布后使用ncbeatuty来移动

总结下问题，希望大佬能伸手指点下
1、vs怎么配置下能实现发布时自动带beauty（我们这会就是乱试，把所有的依赖包，都加上了beauty，所有的*.csproj都加了
```
<PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <MvcRazorCompileOnPublish>true</MvcRazorCompileOnPublish>
    <SatelliteResourceLanguages>zh-Hans</SatelliteResourceLanguages>
    <!--- MvcRazorCompileOnPublish ： 是否对视图进行编译 -->
    <!--<MvcRazorCompileOnPublish>false</MvcRazorCompileOnPublish>-->
    <!--- ServerGarbageCollection ： 服务器垃圾收集 ：不会让内存无限增长 -->
    <ServerGarbageCollection>false</ServerGarbageCollection>
    <!--- ConcurrentGarbageCollection ： 并发垃圾收集 ：不会让内存无限增长 -->
    <ConcurrentGarbageCollection>true</ConcurrentGarbageCollection>
    <UserSecretsId>5138908c-a9c4-47c4-918c-9721cde60011</UserSecretsId>

  <!-- beauty into sub-directory, default is libs, quote with "" if contains space  -->
  <BeautyLibsDir>libraries</BeautyLibsDir>
  <!-- dlls that you don't want to be moved or can not be moved -->
  <!-- <BeautyExcludes>dll1.dll;lib*;...</BeautyExcludes> -->
  <!-- dlls that end users never needed, so hide them -->
  <!-- <BeautyHiddens>hostfxr;hostpolicy;*.deps.json;*.runtimeconfig*.json</BeautyHiddens> -->
  <!-- set to True if you want to disable -->
  <DisableBeauty>False</DisableBeauty>
  <!-- set to True if you don't want to generate NetCoreBeauty flag file -->
  <!-- do not beauty twice since there is no flag file to determine if beauty already -->
  <NoBeautyFlag>False</NoBeautyFlag>
  <ForceBeauty>False</ForceBeauty>
  <!-- <BeautyAfterTasks></BeautyAfterTasks> -->
  <!-- set to True if you want to disable -->
  <DisablePatch>False</DisablePatch>
  <!-- valid values: Error|Detail|Info -->
  <BeautyLogLevel>Info</BeautyLogLevel>
  <!-- set to a repo mirror if you have troble in connecting github -->
   <GitCDN>https://gitee.com/liesauer/HostFXRPatcher</GitCDN> 
   <GitTree>master</GitTree>    
</PropertyGroup> 
  ```
  ```


  <ItemGroup>
...
    <PackageReference Include="nulastudio.NetCoreBeauty" Version="1.2.9.2" />
...
  </ItemGroup>
  ```

使用vs发布时也没有任何效果，只能使用命令：dotnet publish -r alpine-x64 单独指定某个版本，才能生效beauty，但这样就失去了跨平台的意义了

2、有没有相关中文文档指导书（东西是好东西，酒香也怕巷子深啊）
3、有没有相关视频

最后，希望大佬能出些指导文档或视频，博客，这样这个项目才能火起来，更多的人才能用上这么牛逼的东西
尤其针对vs2019设置及操作

**Comment by zhangbest5** [comment]
这代码块引用有问题，我再调下。抱歉

**Comment by liesauer** [comment]
请问你是独立部署的吗？这个工具只有在独立部署的时候才会工作。

**Comment by liesauer** [comment]
`dotnet publish -r`也是跨平台的（分别发布多个平台），只不过这种方式直接把runtime打包好了，双击就能打开，依赖于框架的形式也是跨平台的，只不过这就要求客户机自己安装`.NET Core`运行时（而且也一样要发布多个平台），还有一种部署就是直接发布dll，然后在客户机使用`dotnet xxx.dll`运行，但这种方式显然是不行的

**Comment by liesauer** [comment]
跨平台并不是说一份文件就能在多个平台运行，而是一个App通过跨平台编译成各自平台的文件，各自运行。最本质、最根本的方式还是得每一个平台编译一份，vs最多只是帮你简化了命令操作。

**Comment by zhangbest5** [comment]
感谢大佬回复，不是独立部署，一般我们都是直接发布，一套发布后四处用，有时windows 有时 centos docker

**Comment by zhangbest5** [comment]
![image](https://user-images.githubusercontent.com/55474238/116173662-8e78ed00-a73f-11eb-9670-0ed7088b6165.png)
如图，我们发布完后，是兼容的

**Comment by liesauer** [comment]
不要看rt里面的，看根目录，你看下有多少个可执行程序就知道了

**Comment by liesauer** [comment]
这个工具主要针对场景是面向终端用户的App，不然用户打开软件，找个文件啥的都得找半天，像docker这种的话其实用处不大，所有东西都可以命令实现操作，而且对于真正的用户是不可见的。

**Comment by zhangbest5** [comment]
我是主要做运维的，看着这一片.dll就心烦，想让开发把这些东西像.net mvc时候，该收bin下收进去，这外面扔一胡片，分权限时就不好整

**Comment by zhangbest5** [comment]
![image](https://user-images.githubusercontent.com/55474238/116175279-92f2d500-a742-11eb-978a-fd3548c12dac.png)
发布后的文件

**Comment by zhangbest5** [comment]
![image](https://user-images.githubusercontent.com/55474238/116175308-a140f100-a742-11eb-8b8d-e8b2a7c6bffa.png)
 发布设置，是框架依赖，不是独立，独立就得指定运行环境了吧

**Comment by liesauer** [comment]
对，你独立的话，可以新建多个平台的
![image](https://user-images.githubusercontent.com/8676741/116176055-0c3ef780-a744-11eb-8689-d0515366eee8.png)

至于为什么一定要独立部署才行是因为`.NET Core`的`corehost`中的一个BUG，必须要使用打过补丁后的`apphost`启动程序才行，不然是找不到移动后的文件的，软件是启动不起来的，而且根据这么久的观察（这个项目两年了，但产生做这个工具的想法应该是17年时的），官方并没有要修复相关BUG的意思，所以出路就只有两条：单文件、独立部署+NetCoreBeauty，Fody太复杂了，而且问题很多，不推荐使用

**Comment by zhangbest5** [comment]
那发布完成后，再用ncbeauty下，这种也可行呗？

**Comment by zhangbest5** [comment]
就是在我这种模式下，框架依赖可移植，然后再ncbeauty下，这种没问题吧？

**Comment by liesauer** [comment]
不行，必须要独立部署，因为独立的`apphost`只有独立部署才会生成，这样子才能使用补丁版本的`apphost`，程序加载才不会出问题。

**Comment by zhangbest5** [comment]
好吧，感谢大佬指点
