### ISSUE TITLE
Exception of publish

### ISSUE THREAD

**Issue by zouql** [nulastudio/NetCoreBeauty#28]
严重性 代码 说明 项目 文件 行 禁止显示状态
错误  找到了多个具有相同相对路径的发布输出文件: D:\ProgramData\Nuget\.nuget\packages\system.data.sqlite.core\1.0.113.1\runtimes\win-x64\native\netstandard2.0\SQLite.Interop.dll, D:\ProgramData\Nuget\.nuget\packages\system.data.sqlite.core\1.0.113.1\runtimes\win-x64\native\netstandard2.1\SQLite.Interop.dll。 WebApp  0

**Comment by liesauer** [comment]
按理这个不是由`NetCoreBeauty`造成的错误，将以下配置添加到`csproj`文件重新编译试下：
```xml
<DisableBeauty>True</DisableBeauty>
```

如果重新编译还有这个问题，就不是`NetCoreBeauty`的问题。
