### ISSUE TITLE
Artifact does not exist. v6.0.3/win-x64

### ISSUE THREAD

**Issue by Soar360** [nulastudio/NetCoreBeauty#29]
今天升级了 Visual Studio 后尝试发布，ncbeauty.exe 报错 Artifact does not exist. v6.0.3/win-x64

**Comment by liesauer** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    新的libhostfxr要今晚才能编译

**Comment by liesauer** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    其实并不推荐经常更新vs，因为sdk是和vs绑定的，vs升级了，sdk也都升级了

**Comment by liesauer** [comment]
已上传

**Comment by Soar360** [comment]
谢谢大佬
