### ISSUE TITLE
csproj in different folder breaks NetCoreBeauty

### ISSUE THREAD

**Issue by Apostolique** [nulastudio/NetCoreBeauty#3]
Let's say I have a project in `Source/Hello/World.csproj`.

To publish I can do:

```
dotnet publish Source/Hello -r win-x64 -c Release
```

Specifying the csproj's folder like that makes NetCoreBeauty not apply it's changes (no errors are written in the console though).

If instead I do:
```
cd Source/Hello
dotnet publish -r win-x64 -c Release
```

NetCoreBeauty will work.

**Comment by liesauer** [comment]
fix in [v1.1.6](https://github.com/nulastudio/NetCoreBeauty/releases/tag/v1.1.6), update nuget package to `v1.1.6` will fix.
