### ISSUE TITLE
Missing artifacts for v6.0.6 for NetCoreBeauty

### ISSUE THREAD

**Issue by Ellpeck** [nulastudio/NetCoreBeauty#34]
I was thinking that it might also be nice to have some sort of form (maybe a Google form?) where people can submit missing versions that they need artifacts for, so that this doesn't have to clutter up the issue tracker, and so that these requests are much easier and faster to submit.

Either way, thanks for all your hard work on this project!!

**Comment by liesauer** [comment]
the missing artifacts have been uploaded. and nice suggestion, i will make a from use for reporting missing artifacts.
