### ISSUE TITLE
Manually loaded unmanaged dlls can't be found

### ISSUE THREAD

**Issue by Ellpeck** [nulastudio/NetCoreBeauty#7]
I'm using the [MonoGame Framework](https://github.com/MonoGame/MonoGame) for a project that I am trying to package with NetCoreBeauty. MonoGame loads its unmanaged dependencies (namely SDL) in an odd way, as seen [here](https://github.com/MonoGame/MonoGame/blob/develop/MonoGame.Framework/Platform/Utilities/FuncLoader.Desktop.cs).

When running NetCoreBeauty on a simple example project and trying to run it, the `SDL2.dll` native library can't be found anymore. Moving that file from the `runtimes` folder to the main folder manually fixes the issue.

Here is a simple example project that you can use to recreate the issue: 
[MLEMDesktopGLCoreTest.zip](https://github.com/nulastudio/NetCoreBeauty/files/4456114/MLEMDesktopGLCoreTest.zip) (When run successfully, this project simply displays a window with a black background.)

**Comment by liesauer** [comment]
you are right, any dlls that be loaded by `DllImport` cannot be moved. but unfortunately, NetCoreBeauty cannot determine whether a dll is manually loaded or not. i think the only way to solve this problem is that provide a `BeautyExcludes` property to exclude dlls that you don't want to be moved or can not be moved. a fix will be available soon.

**Comment by Ellpeck** [comment]
That sounds like a pretty good solution. Thanks!

**Comment by liesauer** [comment]
adding `<BeautyExcludes>SDL2*;libSDL2*;sdl2*</BeautyExcludes>` into `csproj` file to avoid moving `SDL2`.
reference:
https://github.com/MonoGame/MonoGame/blob/3b0df35ce1c73435f48953ccd2bb1a8b72c507be/MonoGame.Framework/Platform/SDL/SDL2.cs#L16-L26

**Comment by liesauer** [comment]
UPDATE: after viewing the changes of commit [633b952099](https://github.com/MonoGame/MonoGame/commit/633b952099ebc410af2277a6146c146df887e18d), adding `openal` too for safe.
`<BeautyExcludes>SDL2*;libSDL2*;sdl2*;soft_oal*;openal*</BeautyExcludes>`
