### ISSUE TITLE
Not excluding files causes no files to be moved

### ISSUE THREAD

**Issue by Ellpeck** [nulastudio/NetCoreBeauty#8]
It seems that, when not appending any excluded files for the beautify process, none of the files that should usually get moved actually get moved, resulting in the program doing nothing.

**Comment by liesauer** [comment]
it's a BUG. Empty excluding pattern should be ignored because empty string is basically equals to `.*`. A little trick for you to fix this problem now.
```xml
<BeautyExcludes>never.dll</BeautyExcludes>
```

**Comment by liesauer** [comment]
fixed in `v1.2.8`
