### ISSUE TITLE
Missing 3.1.6 artifact

### ISSUE THREAD

**Issue by lbogdanov** [nulastudio/NetCoreBeauty#9]
First of all, thank you for the great project! I'm currently migrating a project from .net461 to .net core 3.1.6, and glad I found your work as a great replacement for the former "probing privatePath" from App.config

Anyway, I'm getting this error: 
"Artifact does not exist. v3.1.6/win-x64
patch failed"

If I understood correctly, it seems that the latest fx patcher you have is for 3.1.5, would you be able to create a new one for 3.1.6?
Thank you!

**Comment by liesauer** [comment]
uploaded. try rebuilding your project, NetCoreBeauty will fetch the latest artifacts automatically.

**Comment by pietie** [comment]
Hi
Any ETA on .net 5 support?

**Comment by liesauer** [comment]
> Hi
> Any ETA on .net 5 support?

win x86_64 artifacts already uploaded. but linux/mac artifacts still need some time, the build just keeps throwing errors.

**Comment by tdeeb** [comment]
Hi @liesauer, any updates on Linux/Mac artifacts?
